<!doctype html>
<html lang="en" class="scroll-smooth">
@php($profile = $profile ?? null)
@php($settings = $settings ?? collect())
@php($socialLinks = $socialLinks ?? collect())
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $seoTitle ?? ($settings['website_title'] ?? ($profile?->user?->name ?? 'Portfolio')) }}</title><meta name="description" content="{{ $seoDescription ?? ($settings['meta_description'] ?? ($profile?->bio ?? 'Developer portfolio')) }}"><link rel="canonical" href="{{ url()->current() }}"><meta property="og:title" content="{{ $seoTitle ?? ($settings['website_title'] ?? 'Portfolio') }}"><meta property="og:description" content="{{ $seoDescription ?? ($settings['meta_description'] ?? 'Developer portfolio') }}"><meta property="og:url" content="{{ url()->current() }}"><meta property="og:type" content="website">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="public-shell bg-[#101010] text-white antialiased">
<header class="public-header sticky inset-x-0 top-0 z-50 border-b border-white/[.06] bg-[#101010]/95 backdrop-blur-xl"><div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><a href="{{ route('home') }}" class="text-xl font-bold tracking-tight text-white">{{ $settings['logo_text'] ?? 'LOGO' }}<span class="text-orange-500">.</span></a><nav class="hidden flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm xl:flex">@foreach([['home','Home'],['about','About'],['skills','Skills'],['projects','Projects'],['experience','Experience'],['education','Education'],['certificates','Certificates'],['blog','Blog'],['contact','Contact']] as [$route,$label])<a href="{{ route($route) }}" class="{{ request()->routeIs($route) ? 'text-orange-500 font-semibold' : 'text-white/55 hover:text-white' }}">{{ $label }}</a>@endforeach</nav><div class="flex items-center gap-3"><a href="{{ $profile?->cv_path ? asset('storage/'.$profile->cv_path) : route('contact') }}" class="hidden rounded-md bg-orange-500 px-5 py-2.5 text-sm font-semibold text-white sm:inline-block">Download CV</a><button id="public-menu" class="text-xl text-white xl:hidden" aria-label="Open menu">☰</button></div></div><nav id="public-mobile-menu" class="hidden border-t border-white/10 bg-[#151515] px-6 py-4 xl:hidden">@foreach([['home','Home'],['about','About'],['skills','Skills'],['projects','Projects'],['experience','Experience'],['education','Education'],['certificates','Certificates'],['blog','Blog'],['contact','Contact']] as [$route,$label])<a href="{{ route($route) }}" class="block border-b border-white/5 py-3 text-sm text-white/70">{{ $label }}</a>@endforeach</nav></header>
<main>@if(session('success'))<div class="mx-auto max-w-7xl px-6 pt-6"><div class="rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-5 py-4 text-emerald-200">{{ session('success') }}</div></div>@endif @yield('content')</main>
<footer class="border-t border-white/10 bg-[#0b0b0b]"><div class="mx-auto grid max-w-7xl gap-10 px-6 py-14 md:grid-cols-3"><div><div class="text-xl font-bold">{{ $profile?->user?->name ?? 'Portfolio' }}<span class="text-orange-500">.</span></div><p class="mt-4 text-sm leading-7 text-white/45">{{ $profile?->bio ?? 'Thoughtful digital products, dependable code, and useful experiences.' }}</p></div><div><h3 class="font-semibold">Explore</h3><div class="mt-4 grid gap-2 text-sm text-white/50"><a href="{{ route('projects') }}">Selected work</a><a href="{{ route('blog') }}">Writing</a><a href="{{ route('contact') }}">Let’s work together</a></div></div><div><h3 class="font-semibold">Connect</h3><div class="mt-4 flex flex-wrap gap-3">@foreach($socialLinks as $link)<a href="{{ $link->url }}" target="_blank" rel="noreferrer" class="rounded-full border border-white/10 px-3 py-1.5 text-sm text-white/60 hover:border-orange-500 hover:text-orange-500">{{ $link->name }}</a>@endforeach</div></div></div><div class="border-t border-white/10 px-6 py-6 text-center text-xs text-white/35">© {{ date('Y') }} {{ $profile?->user?->name ?? 'Portfolio' }}. All rights reserved.</div></footer>
<script>document.getElementById('public-menu')?.addEventListener('click',()=>document.getElementById('public-mobile-menu').classList.toggle('hidden'));</script>
</body></html>
